# Generated by Django 5.2.1 on 2025-07-02 18:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articolo',
            fields=[
                ('id_articolo', models.AutoField(primary_key=True, serialize=False)),
                ('titolo', models.CharField(max_length=200)),
                ('testo', models.TextField()),
                ('data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='spider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('eta', models.IntegerField()),
                ('sesso', models.CharField(max_length=10)),
                ('specie', models.CharField(max_length=50)),
                ('icona', models.CharField(max_length=100)),
                ('unita_eta', models.CharField(default='anni', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='utenti',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('data_creazione', models.DateTimeField(default=django.utils.timezone.now)),
                ('livello', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('data', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='eventi_foto/')),
                ('id_tarantola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventi', to='My_Spider.spider')),
            ],
        ),
        migrations.AddField(
            model_name='spider',
            name='utente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='My_Spider.utenti'),
        ),
        migrations.CreateModel(
            name='Seguito',
            fields=[
                ('id_seguito', models.AutoField(primary_key=True, serialize=False)),
                ('id_utente_seguace', models.ForeignKey(db_column='id_utente_seguace', on_delete=django.db.models.deletion.CASCADE, related_name='seguiti', to='My_Spider.utenti')),
                ('id_utente_seguito', models.ForeignKey(db_column='id_utente_seguito', on_delete=django.db.models.deletion.CASCADE, related_name='seguaci', to='My_Spider.utenti')),
            ],
        ),
        migrations.CreateModel(
            name='Interazione_Evento',
            fields=[
                ('id_interazione', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=20)),
                ('testo_commento', models.TextField(blank=True)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_evento', models.ForeignKey(db_column='id_evento', on_delete=django.db.models.deletion.CASCADE, to='My_Spider.evento')),
                ('id_utente', models.ForeignKey(db_column='id_utente', on_delete=django.db.models.deletion.CASCADE, to='My_Spider.utenti')),
            ],
        ),
        migrations.CreateModel(
            name='Interazione_Articolo',
            fields=[
                ('id_interazione', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=20)),
                ('testo_commento', models.TextField(blank=True)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_articolo', models.ForeignKey(db_column='id_articolo', on_delete=django.db.models.deletion.CASCADE, to='My_Spider.articolo')),
                ('id_utente', models.ForeignKey(db_column='id_utente', on_delete=django.db.models.deletion.CASCADE, to='My_Spider.utenti')),
            ],
        ),
        migrations.AddField(
            model_name='articolo',
            name='id_utente',
            field=models.ForeignKey(db_column='id_utente', on_delete=django.db.models.deletion.CASCADE, to='My_Spider.utenti'),
        ),
    ]
