# Generated by Django 5.2.1 on 2025-05-28 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_Spider', '0002_utenti_livello'),
    ]

    operations = [
        migrations.CreateModel(
            name='spider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('eta', models.IntegerField()),
                ('sesso', models.CharField(max_length=10)),
                ('specie', models.CharField(max_length=50)),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='My_Spider.utenti')),
            ],
        ),
    ]
