# Generated by Django 5.2.1 on 2025-06-10 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_Spider', '0003_spider'),
    ]

    operations = [
        migrations.AddField(
            model_name='spider',
            name='icona',
            field=models.CharField(default='default.png', max_length=100),
        ),
    ]
