# Generated by Django 5.2.1 on 2025-06-10 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_Spider', '0004_spider_icona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spider',
            name='icona',
            field=models.CharField(max_length=100),
        ),
    ]
