# Generated by Django 5.2.1 on 2025-06-10 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_Spider', '0005_alter_spider_icona'),
    ]

    operations = [
        migrations.AddField(
            model_name='spider',
            name='unita_eta',
            field=models.CharField(default='anni', max_length=10),
        ),
    ]
