# Generated by Django 5.2.1 on 2025-07-01 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_Spider', '0006_spider_unita_eta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('data', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='eventi_foto/')),
                ('id_tarantola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventi', to='My_Spider.spider')),
            ],
        ),
    ]
