# Generated by Django 5.2.1 on 2025-07-02 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_Spider', '0007_evento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articolo',
            fields=[
                ('id_articolo', models.AutoField(primary_key=True, serialize=False)),
                ('titolo', models.CharField(max_length=200)),
                ('testo', models.TextField()),
                ('data', models.DateField()),
                ('id_utente', models.ForeignKey(db_column='id_utente', on_delete=django.db.models.deletion.CASCADE, to='My_Spider.utenti')),
            ],
        ),
    ]
